name: Publish package to GitHub Registry

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch --all --tags
          git checkout -b temp-branch ${{ github.sha }}
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      